### ISSUE TITLE
[LOOK INTO] Sometimes image can not zoom and double click doesn't work both on Android and iOS.

### ISSUE THREAD

**Issue by csyaonie** [Luehang/react-native-gallery-swiper#14]
double click function not work,when i use two finger to zoom the image,it back to origin size immediately when move up 

双击图片 有时候无法放大，我滑动几下 又回来 这张图片又可以 放大了，双击无法放大的图片再用双指放大 图片有变大 手放开马上又回去了

**Comment by Luehang** [comment]
Hi,

Can you provide your code that you use, package version and which platform along with anything else that is useful?

**Comment by Luehang** [comment]
Hi,

This actually isn't a bug.  The original image size is too small.  Under the hood, it is using `Math.max(imageWidth / viewWidth, imageHeight / viewHeight)`.

# :books: Props

Props | Description | Type | Default
------ | ------ | ------ | ------
`maxScale` | Max zoom (view transformer). **Version \*1.17.0 update**. | `number` | `Math.max(imageWidth / viewWidth, imageHeight / viewHeight)`

To zoom for this tiny image, set the prop `maxScale` to `> 1`.  This will cause pixelated images because the image is small.

**Comment by Luehang** [comment]
If you like [`react-native-gallery-swiper`](https://github.com/Luehang/react-native-gallery-swiper), please be sure to give it a star at [GitHub](https://github.com/Luehang/react-native-gallery-swiper). Thanks.
