### ISSUE TITLE
Swipe does not feel entirely native on iOS

### ISSUE THREAD

**Issue by andresmanikis** [Luehang/react-native-gallery-swiper#2]
Hey, impressive work with this library. By far, the best one among the ones I took a look of. The only thing I noticed is that when you swipe between images it doesn't feel entirely natural, at least in iOS. I think the speed at which the images scroll is a bit slow. I'd expect them to move much faster.

Here's a video in which I try to make this point as clear as possible (sorry I can't upload the video directly, GitHub won't let me): 
[IMG_4250.TRIM.MOV.zip](https://github.com/Luehang/react-native-gallery-swiper/files/2673983/IMG_4250.TRIM.MOV.zip)

Thanks a lot!
Andrés

**Comment by Luehang** [comment]
Hi, thanks for trying to point that out.  It is normal for the scroller to react like that, because the animation is suppose to land softly and slowly to the end when it is being "flinged."  If you try shorter and slower swipe and release to the left and right, it will be a lot faster and there will be no cushion at the end.

**Comment by Luehang** [comment]
Hi, I just updated this package, and if you would like you can disable the intelligent detection that "cushion" or slow down a rough swipe at the end.

Props | Description | Type | Default
------ | ------ | ------ | ------
`sensitiveScroll` | Whether to enable an intelligent detection to detect rough and fast swiping gestures in order to "cushion" or slow down a swipe at the end. **Version ^1.4.0 update**. | `Boolean` | `true`

Always happy to help.
