### ISSUE TITLE
Scrolling is slow and laggy.

### ISSUE THREAD

**Issue by lxndr** [Luehang/react-native-gallery-swiper#4]
Hi.
I experience quite laggish behavior while scrolling left and right. I noticed that the image component re-renders really often and that could be the cause of the lags. I also noticed that renderRow is called constantly while swiping.

**Comment by Luehang** [comment]
Hi,

<br/>

I will take your feedback and help improve this package. Thanks for the input. Much needed.

This free open source package has not been improved often, and I have not had the time to look into the root of these issues you claim. Sooner or later in the future, there will be a lot of improvements and updates you will be seeing.

A little about the scrolling... It is normal for the scroller to react like that, because the animation is suppose to land softly and slowly to the end when it is being "flinged." If you try shorter and slower swipe and release to the left and right, it will be a lot faster and there will be no cushion at the end.

Try this if it helps solve the issue.

# 🔹  Props

Props | Description | Type | Default
------ | ------ | ------ | ------
`sensitiveScroll` | Detect rough and fast swiping gestures in order to "cushion" or slow down a swipe at the end. **Version \*1.4.0 update**. | `Boolean` | `true`

I will look into the re-renderer and see what I can do.

<br/>
<br/>

From,

Lue Hang

**Comment by Luehang** [comment]
Hi,

There has been a new update and solution to this problem.  Check out the new update.  The image component now only renders a `imageLoaded` to `true` and renders the `image` once.  If you like `react-native-gallery-swiper`, be sure to give it a star!  Thanks.

<br/>

## :large_blue_diamond: Performance Optimization List Example

```javascript
import GallerySwiper from "react-native-gallery-swiper";

//...
render() {
    return (
        <GallerySwiper
            style={{ flex: 1, backgroundColor: "black" }}
            images={[
                { uri: "https://luehangs.site/pic-chat-app-images/beautiful-blond-blonde-hair-478544.jpg",
                    // Optional: Adding a dimensions or height and
                    // width field with the actual width and height
                    // for REMOTE IMAGES will help improve performance.
                    dimensions: { width: 1080, height: 1920 } },
                { uri: "https://luehangs.site/pic-chat-app-images/beautiful-beautiful-women-beauty-40901.jpg",
                    dimensions: { width: 1080, height: 1920 } },
                { uri: "https://luehangs.site/pic-chat-app-images/animals-avian-beach-760984.jpg",
                    dimensions: { width: 1080, height: 1920 } },
                { uri: "https://luehangs.site/pic-chat-app-images/beautiful-blond-fishnet-stockings-48134.jpg",
                    dimensions: { width: 1080, height: 1920 } },
                { uri: "https://luehangs.site/pic-chat-app-images/beautiful-beautiful-woman-beauty-9763.jpg",
                    dimensions: { width: 1080, height: 1920 } },
                { uri: "https://luehangs.site/pic-chat-app-images/attractive-balance-beautiful-186263.jpg",
                    dimensions: { width: 1920, height: 1080 } },
                // Test with 10 to over 100s to 1000s of images
                // ...
                // ...
                // ...
            ]}
            // Change this to render how many items before it.
            initialNumToRender={2}
            // Turning this off will make it feel faster
            // and prevent the scroller to slow down
            // on fast swipes.
            sensitiveScroll={false}
        />
    );
}
//...
```
