### ISSUE TITLE
Missing credit for original author

### ISSUE THREAD

**Issue by gp3gp3gp3** [Luehang/react-native-gallery-swiper#56]
This repo is a copy paste of https://github.com/archriss/react-native-image-gallery.  Maintainer keeps closing issues related to this.

See:
https://github.com/Luehang/react-native-gallery-swiper/pull/44
https://github.com/Luehang/react-native-gallery-swiper/issues/55
https://github.com/Luehang/react-native-gallery-swiper/issues/54

**Comment by Luehang** [comment]
If this is a copy and paste, then don't use it!!  Clearly, it isn't.

**Comment by gp3gp3gp3** [comment]
I don't use it, and wouldn't for this reason

**Comment by Luehang** [comment]
You are making false accusations.

**Comment by shubhaemk** [comment]
It's not about being a copy - paste. Just credit the original author. Please.

**Comment by gp3gp3gp3** [comment]
If anyone is looking for a gallery solution to this not maintained by this person, this repo has a great full image swipe-able example https://github.com/wcandillon/can-it-be-done-in-react-native/tree/master/season3/src/WhatsApp

**Comment by Luehang** [comment]
`react-native-image-gallery` is suppose to have this. 

<br/>

```
Copyright (c) <date> ldn0x7dc 
```

**Comment by satya164** [comment]
You should include an attribution just out of respect for the original author, regardless of whether it's legal or not.

Besides, according to the ISC license, you must include the copyright notice and full license text. The original package didn't include the text, which is a mistake.

**Comment by Luehang** [comment]
If mine is part of that, I would include this.

```
Copyright (c) <date> ldn0x7dc 
```

**Comment by Luehang** [comment]
The whole time, maintainers are not putting down.

```
Copyright (c) <date> ldn0x7dc 
```

**Comment by satya164** [comment]
"I'll ignore doing it because they made a mistake" doesn't sound very mature.

**Comment by Luehang** [comment]
You're talking about being mature.  You're making this very pity.

**Comment by romanonthego** [comment]
right, @satya164 is the one making this pity...

**Comment by satya164** [comment]
What's your reason for not crediting the author? It's a nice thing to do.

**Comment by wooorm** [comment]
@Luehang I’m happy that you seem to have changed your mind. Per your comment just now, indeed, it should have something like that!

If a project does not have a license, it’s not open source. That is a mistake on their part, but copyright exists in such a way that you don’t need to say you have copyright! You have it anyway! They did decide on an ISC license, which includes a clause that says you are free to create a derivative work, but *must* include the original copyright statement.

For a fix, [I suggested](https://github.com/Luehang/react-native-gallery-swiper/issues/54#issue-648344276) to use the company name, because it seems that the project was made in employment of that organization instead of that username. Now: it is in fact up to you to find out who has the copyright, before creating a derivative work.

So, I suggest you try and reach out to the original authors, on what name they’d want to be used. If they don’t respond, the company name / original username / a mention in the readme is fine!

Finally, everybody sees that you are helping maintain an unmaintained project, adding fixes and features on top, that’s great. But folks are also seeing you double down, and frankly, not being a good person in open source.

**Comment by jamiebuilds** [comment]
Lue, no one started off angry with you. You didn't need to go on the defensive, you've only drawn more attention by doing so. No one is threatening to sue you, no one is saying they don't appreciate your work, no one is saying it was wrong of you to fork someone else's code.

You've used open source correctly and given something of value. You haven't broken any laws, you haven't hurt anyone.

But as an open source author myself, I appreciate when people credit me when they take my work and run with it. Even when I license things in the most permissive way I can, it sucks when someone forks my work and doesn't credit me. It feels like they lack respect for my work.

**Comment by thblckjkr** [comment]
The notice was on the readme on the [first commit](https://github.com/Luehang/react-native-gallery-swiper/commit/6705f094f7bc510ff4a166514b5477ae742e2ff1?diff=unified#diff-04c6e90faac2675aa89e2176d2eec7d8R15). I wonder what made him change his mind.

**Comment by nico-abram** [comment]
@Luehang If I understand correctly you're trying to claim that "No copyright notice and no license" means it's up for free. This is not correct. It is actually *worse* for someone looking to use a library if it has none of those. Things aren't public domain by default (And "public domain" is iirc not a thing in some countries). If it's unlicensed you are actually in shakier grounds than if they used a FOSS non copyleft license like MIT. Just wanted to clarify that.

**Comment by ocdtrekkie** [comment]
Looks like he deleted the credit to the original library (which wasn't even a link to their GitHub repo) four months into this repo's lifespan. It's kinda funny because half way through that he edited the name of the original library (which made it incorrect) as well. But it was far from an oversight that the line was there. He just seems to have changed his mind about acknowledging the original author wrote the original code.
