### ISSUE TITLE
Credit the original dev

### ISSUE THREAD

**Issue by JosephTico** [Luehang/react-native-gallery-swiper#57]
You're being mocked on Twitter:

https://twitter.com/satya164/status/1277988371579707392?s=19

Your attitude is disgusting.

**Comment by rcstr** [comment]
mae perrito, es vara discutir con este mae

**Comment by REBELinBLUE** [comment]
I love how he thinks that anyone questioning his behaviour is a junior developer... which also shows what sort of person he is because he thinks someone who is a junior is beneath a senior or lead developer and worthy of contempt rather than someone who a senior or lead should mentor and help to learn

**Comment by JosephTico** [comment]
> mae perrito, es vara discutir con este mae

No esperaba encontrar un comentario en español aquí 😂

**Comment by Luehang** [comment]
You guys are bullies.  And you're not being the bigger person.  `archriss` is not the owner.

**Comment by alanzeino** [comment]
> you're not being the bigger person

you insulted people in #44 as 'junior developers' even though you clearly have copied someone else's repo as a marketing exercise, you barely respond to issues on your repo, your entire bio is made up and all the self–proclaimed titles you've given yourself are bullshit, and you just seem like a jerk asshole overall and now that you're getting heat you double down instead of apologizing and just adding the damn credit???!!
